web_personal/core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= "core"
urlpatterns = [
    path('',views.home,name="home"),
    path('about-me/',views.about,name="about"),
    path('contact/',views.contact,name="contact"),
]

web_personal/portfolio/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name= "portfolio"
urlpatterns = [
    path('',views.portfolio,name="portfolio"),
]

web_personal/web_personal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path('portfolio/',include("portfolio.urls"))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

web_personal/core/models.py
from django.db import models

# Create your models here.

web_personal/portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=200, verbose_name="titulo")
    description = models.TextField(verbose_name="descripcion")
    image = models.ImageField(verbose_name="imagen",upload_to="projects")
    link = models.URLField(null=True,blank=True,verbose_name="enlace")
    created = models.DateTimeField(auto_now_add=True,verbose_name="fecha de creacion")
    update = models.DateTimeField(auto_now=True,verbose_name="fecha de edicion")

    class Meta:
        verbose_name = "proyecto"
        verbose_name_plural = "proyectos"
        ordering =["-created"]

    def __str__(self):
        return self.title

web_personal/core/views.py
from django.shortcuts import render , HttpResponse

# Create your views here.
def home(request):
    return render(request,'core/home.html')


def about(request):
    return render(request,'core/about.html')


def contact(request):
    return render(request,'core/contact.html')

web_personal/portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def portfolio(request):
    projects = Project.objects.all()
    return render(request,'portfolio/portfolio.html',{
        'projects':projects,
    })

web_personal/core/templates/core/about.html
{% extends "./base/index.html" %}
{% load static %}
{% block title %}Juan Pérez{% endblock title %}

{% block background %}{% static "core/img/about-bg.jpg" %}{% endblock background %}
{% block headers %}
<h1>Acerca de</h1>
<span class="subheading">Biografía</span>
{% endblock headers %}
{% block content %}
<!-- Contenido Principal -->
  <div class="container">
    <div class="row">   
      <div class="col-lg-3 col-md-4 offset-lg-1">
        <img class="img-fluid avatar" src="{% static "core/img/avatar.jpg" %}" alt="">
      </div>
      <div class="col-lg-7 col-md-8">
        <h2 class="section-heading">Juan Pérez</h2>   
        <p>Nacido en... lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit...</p>
      </div>
    </div>  
  </div>
{% endblock content %}

web_personal/core/templates/core/base/footer.html
<!-- Pié de página -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                <li class="list-inline-item">
                    <a href="#">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                    </span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a href="#">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                    </span>
                    </a>
                </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; 2018 · Juan Pérez (Ingeniero Industrial) </p>
            </div>
        </div>
    </div>
</footer>

web_personal/core/templates/core/base/header.html
<!-- Navegación -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="{% url "core:home" %}">Juan Pérez</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menú
      <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url "core:home" %}">Portada</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "core:about" %}">Acerca de</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "portfolio:portfolio" %}">Portafolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "core:contact" %}">Contacto</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

web_personal/core/templates/core/base/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
      {% block title %}
      {% endblock title %}
    </title>

    <!-- Estilos y fuentes del template  -->
    <link href="{% static "core/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "core/vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static "core/css/clean-blog.min.css" %}" rel="stylesheet">

  </head>

  <body>

    {% include "./header.html" %}
    {% comment %} Contenido {% endcomment %}
      <!-- Cabecera -->
    <header class="masthead" style="background-image: url('{% block background %}{% endblock background %}')">
        <div class="overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <div class="site-heading">
                {% block headers %}{% endblock headers %}
              </div>
            </div>
          </div>
        </div>
    </header>

    {% block content %}
    
    {% endblock content %}
    {% if request.path != "/" %}
    <hr>
    {% endif %}
    

    {% include "./footer.html" %}

    <!-- Bootstrap y Javascripts -->
    <script src="{% static "core/vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "core/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "core/js/clean-blog.min.js" %}"></script>

  </body>

</html>

web_personal/core/templates/core/contact.html
{% extends "./base/index.html" %}

{% block title %}Juan Pérez{% endblock title %}

{% block background %}{% load static %}{% static "core/img/contact-bg.jpg" %}{% endblock background %}
{% block headers %}
  <h1>Contacto</h1>
  <span class="subheading">Asesoría</span>
{% endblock headers %}
{% block content %}
  <!-- Contenido Principal -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <br>
        <p><b>Teléfono:</b> +09 876 543 210</p>
        <p><b>Honorarios:</b> 60€/h (precio base)</p>
      </div>
    </div>
  </div>
{% endblock content %}

web_personal/core/templates/core/home.html
{% extends "./base/index.html" %}

{% block title %}Juan Pérez{% endblock title %}

{% block background %}{% load static %}{% static "core/img/home-bg.jpg" %}{% endblock background %}
{% block headers %}
    <h1>
        Juan Pérez
    </h1>
    <span class="subheading">
        Ingeniero Industrial
    </span>
{% endblock headers %}

{% block content %}

{% endblock content %}

web_personal/portfolio/templates/portfolio/portfolio.html
{% extends "core/base/index.html" %}

{% block title %}Juan Pérez{% endblock title %}

{% block background %}{% load static %}{% static "core/img/portfolio-bg.jpg" %}{% endblock background %}
{% block headers %}
	<h1>Portafolio</h1>
	<span class="subheading">Currículo</span>
{% endblock headers %}

{% block content %}
	<!-- Contenido Principal -->
	<div class="container">
		<!-- Proyectos -->
		{% for project in projects %}
		<div class="row project">  	
			<div class="col-lg-3 col-md-4 offset-lg-1">
				<img class="img-fluid" src="{{project.image.url}}" alt="">
			</div>
			<div class="col-lg-7 col-md-8">
				<h2 class="section-heading title">{{project.title}}</h2>   
				<p>{{project.description}}</p>
				{% if project.link %}
				<p><a href="{{project.link}}">Más información</a></p>
				{% endif %}
			</div>
		</div>
		{% endfor %}

{% endblock content %}